# Generated by Django 6.0.5 on 2026-05-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
        ('accounts', '0005_rename_message_booking_notes_and_more'),
    ]

    operations = [
    ]
